# Generated by Django 4.1.5 on 2023-01-05 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_tag_article_tags"),
    ]

    operations = [
        migrations.RenameModel(old_name="Tag", new_name="Tag2",),
    ]
