# Generated by Django 4.1.5 on 2023-01-05 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_rename_tag_tag2"),
    ]

    operations = [
        migrations.RenameModel(old_name="Tag2", new_name="Tag",),
    ]
